dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/odc
dependency_branch: develop
parallelism_factor: 8
self_build: false # Only for python packages
