repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace     # Trailing whitespace checker
  - id: end-of-file-fixer     # Ensure files end in a newline
  - id: check-json
  - id: check-yaml     # Check YAML files for syntax errors only
    args: [--unsafe, --allow-multiple-documents]
  - id: check-toml
          # - id: check-added-large-files
  - id: debug-statements     # Check for debugger imports and py37+ breakpoint()
  - id: mixed-line-ending
  - id: no-commit-to-branch     # Prevent committing to main / master
  - id: check-merge-conflict     # Check for files that contain merge conflict
    exclude: /README\.rst$|^docs/.*\.rst$
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
  - id: ruff-check
    exclude: '(dev/.*|.*_)\.py$'
    args:
    - --line-length=120
    - --fix
    - --exit-non-zero-on-fix
    - --preview
  - id: ruff-format
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.14
  hooks:
  - id: mdformat
    exclude: cruft-update-template.md
- repo: https://github.com/google/yamlfmt
  rev: v0.13.0
  hooks:
  - id: yamlfmt
- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v1.0.0
  hooks:
  - id: sphinx-lint
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.5.0"
  hooks:
  - id: pyproject-fmt
