#!/usr/bin/env python
"""Clean up sphinx-apidoc generated RST files.

This script post-processes the RST files generated by sphinx-apidoc to:
1. Remove private modules (those starting with '_')
2. Remove hidden modules (configured in conf.py)
3. Update toctree entries to use short display names in the sidebar
   while keeping full module paths as page titles
4. Replace automodule directives with autosummary tables (optional)
5. Rename page headings by stripping "package"/"module" suffixes (optional)
6. Inject :titlesonly: into toctree directives (optional)

All steps are individually controlled via flags in conf.py — see the
feature-flag block there for the full list and defaults.
"""

import importlib
import inspect
import re
import sys
import types
from pathlib import Path

# Ensure conf.py's directory is on sys.path so it can be imported when this
# script is run directly from any working directory.
_DOCS_SOURCE_DIR = str(Path(__file__).resolve().parent)
if _DOCS_SOURCE_DIR not in sys.path:
    sys.path.insert(0, _DOCS_SOURCE_DIR)

# Import configuration from conf.py.
# conf.py owns the sys.path setup for the project src directory.
import conf

DOCS_DIR = Path(__file__).parent
AUTODOCS_DIR = DOCS_DIR / getattr(conf, "autodocs_dir", "autodocs")
MODULE_PREFIX: str = conf.module_prefix  # e.g., 'earthkit.transforms'

# ---------------------------------------------------------------------------
# Feature flags — read from conf.py with backward-compatible defaults
# ---------------------------------------------------------------------------
_delete_hidden: bool = getattr(conf, "autodocs_delete_hidden", True)
_replace_automodule: bool = getattr(conf, "autodocs_replace_automodule", True)
_short_display_names: bool = getattr(conf, "autodocs_short_display_names", True)
_top_level_maxdepth: int | None = getattr(conf, "autodocs_top_level_maxdepth", 1)
_rename_titles: bool = getattr(conf, "autodocs_rename_titles", False)
_top_level_title: str = getattr(conf, "autodocs_top_level_title", "API Reference")
_titlesonly: bool = getattr(conf, "autodocs_titlesonly", False)
_use_package_all_definition: bool = getattr(conf, "autodocs_use_package_all_definition", True)
_hide_from_sidebar: bool = getattr(conf, "autodocs_hide_from_sidebar", False)
_skip_members: dict[str, list[str]] = getattr(conf, "autodocs_skip_members", {})


def get_hidden_modules() -> list[str]:
    """Get the list of hidden modules from conf.py."""
    return getattr(conf, "autodocs_hidden_modules", [])


def is_private_module(module_name: str) -> bool:
    """Check if a module is private (starts with '_')."""
    # Get the last part of the module name
    parts = module_name.split(".")
    return any(part.startswith("_") for part in parts)


def should_hide_module(module_name: str, hidden_modules: list[str]) -> bool:
    """Check if a module should be hidden from documentation.

    Args:
        module_name: Full module name (e.g., 'earthkit.transforms.aggregate')
        hidden_modules: List of module names to hide (relative to earthkit.transforms)

    Returns:
        True if the module should be hidden.

    """
    if is_private_module(module_name):
        return True

    # Check against hidden modules list
    for hidden in hidden_modules:
        full_hidden = f"{MODULE_PREFIX}.{hidden}"
        # Match exact module or submodules
        if module_name == full_hidden or module_name.startswith(f"{full_hidden}."):
            return True

    return False


def get_short_name(module_name: str) -> str:
    """Get the short display name for a module.

    Args:
        module_name: Full module name (e.g., 'earthkit.transforms.temporal')

    Returns:
        Short name (e.g., 'temporal')

    """
    if module_name.startswith(f"{MODULE_PREFIX}."):
        return module_name[len(MODULE_PREFIX) + 1 :]
    return module_name


def _get_module_api_from_all(module: types.ModuleType) -> list[str]:
    """Return public API members using the module's ``__all__`` attribute."""
    all_names = list(getattr(module, "__all__", []))
    return [
        name for name in all_names
        if not isinstance(getattr(module, name, None), types.ModuleType)
        and not (name.startswith("__") and name.endswith("__"))
    ]


def _get_module_api_from_inspect(module: types.ModuleType, module_name: str) -> list[str]:
    """Return public API members by inspecting the module's contents.

    Discovers all public names (not starting with ``_``) that are defined in
    the module itself (i.e. whose ``__module__`` matches *module_name*).
    Sub-modules are excluded because they are already represented in the
    toctree.
    """
    members = []
    for name, obj in inspect.getmembers(module):
        # Skip private / dunder names
        if name.startswith("_"):
            continue
        # Skip sub-modules (handled by toctree)
        if isinstance(obj, types.ModuleType):
            continue
        # Only include objects defined in this module
        obj_module = getattr(obj, "__module__", None)
        if obj_module is not None and obj_module != module_name:
            continue
        members.append(name)
    return members


def get_module_api(module_name: str) -> list[str]:
    """Get the public API of a module.

    When ``autodocs_use_package_all_definition`` is True (the default),
    the module's ``__all__`` attribute is used.  When False, the module
    is introspected for all public names defined within it.  However,
    if the module defines ``__all__`` it is always respected regardless
    of the flag, since it represents an explicit API declaration.

    Args:
        module_name: Full module name (e.g., 'earthkit.transforms.temporal')

    Returns:
        List of public member names, or empty list if not available.

    """
    try:
        module = importlib.import_module(module_name)
        has_all = hasattr(module, "__all__") and module.__all__
        if _use_package_all_definition or has_all:
            members = _get_module_api_from_all(module)
        else:
            members = _get_module_api_from_inspect(module, module_name)

        # Apply per-module skip list
        blocked = _skip_members.get(module_name, [])
        if blocked:
            members = [m for m in members if m not in blocked]

        return members
    except ImportError as exc:
        print(f"Warning: could not import {module_name}: {exc}")
        return []


def _is_rst_underline(line: str) -> bool:
    """Return True if *line* looks like an RST heading underline."""
    s = line.strip()
    return len(s) >= 2 and len(set(s)) == 1 and s[0] in "=-~^*+#"


def rename_titles(content: str) -> str:
    """Rename RST page headings generated by sphinx-apidoc.

    - Replaces the top-level package heading (``MODULE_PREFIX package``) with
      ``_top_level_title``.
    - Strips the " package" / " module" suffix from all other headings.

    The RST underline is resized to match the new title length.

    Args:
        content: RST file content.

    Returns:
        Updated RST content.

    """
    lines = content.split("\n")
    result: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Only attempt title processing when the next line is an RST underline.
        if i + 1 < len(lines) and _is_rst_underline(lines[i + 1]):
            underline_char = lines[i + 1].strip()[0]

            # Top-level package/module heading → custom title.
            if re.match(rf"^{re.escape(MODULE_PREFIX)}\s+(package|module)$", stripped):
                new_title = _top_level_title
                result.append(new_title)
                result.append(underline_char * len(new_title))
                i += 2
                continue

            # Submodule/subpackage heading → strip " package"/" module" suffix.
            match = re.match(r"^([\w\.\\]+)\s+(package|module)$", stripped)
            if match:
                new_title = match.group(1)
                result.append(new_title)
                result.append(underline_char * len(new_title))
                i += 2
                continue

        result.append(line)
        i += 1

    return "\n".join(result)


def replace_automodule_with_autosummary(content: str, module_name: str) -> str:
    """Replace the automodule :members: block with an autosummary table.

    The module docstring is preserved via a bare ``.. automodule::`` directive
    (without ``:members:``).  A ``.. autosummary::`` table with a per-module
    ``:toctree:`` subdirectory is appended so that sphinx-build generates a
    dedicated HTML page for every public function.

    Args:
        content: RST file content
        module_name: Full module name (e.g., 'earthkit.transforms.temporal')

    Returns:
        Updated RST content.

    """
    members = get_module_api(module_name)
    short_name = get_short_name(module_name)

    # Always produce a bare automodule (docstring only — no inherited :members:
    # options) to avoid documenting imported members inline, which would clash
    # with the per-function pages generated by autosummary.
    # The :no-members: / :no-imported-members: directives explicitly override
    # the autodoc_default_options set in conf.py.
    block_lines = [
        f".. automodule:: {module_name}",
        "   :no-members:",
        "   :no-imported-members:",
        "",
    ]

    if members:
        block_lines += [
            f".. currentmodule:: {module_name}",
            "",
            ".. autosummary::",
            "   :toctree: generated/" + short_name,
            "",
        ]
        for member in members:
            block_lines.append(f"   {member}")
        block_lines.append("")

    new_block = "\n".join(block_lines)

    # Replace the entire automodule block (with any autodoc options) that
    # sphinx-apidoc emits.  The block starts with ``.. automodule::`` and
    # continues through consecutive option lines (``   :option:``).
    content = re.sub(
        r"\.\. automodule::[ \t]+" + re.escape(module_name) + r"(?:\n[ \t]+:.*)*\n",
        new_block + "\n",
        content,
    )
    return content


def clean_toctree(
    content: str,
    hidden_modules: list[str],
    max_depth: int | None = None,
    short_names: bool = True,
    titlesonly: bool = False,
    hidden: bool = False,
) -> str:
    """Clean up toctree entries in RST content.

    - Removes entries for hidden/private modules
    - Optionally rewrites entries to use short display names:
      ``temporal <earthkit.transforms.temporal>``
    - Optionally overrides :maxdepth: to control how deep the TOC renders
    - Optionally injects :titlesonly: when absent
    - Optionally injects :hidden: so toctrees don't appear in the sidebar

    Args:
        content: RST file content
        hidden_modules: List of module names to hide
        max_depth: If set, replaces :maxdepth: in every toctree with this number.
            This only affects rendering depth; all linked pages are still built.
        short_names: If True, rewrite toctree entries to use the short module
            name as the display label.
        titlesonly: If True, inject ``:titlesonly:`` into toctrees that lack it.
        hidden: If True, inject ``:hidden:`` into toctrees that lack it.

    Returns:
        Updated RST content

    """
    lines = content.split("\n")
    result_lines: list[str] = []
    in_toctree = False
    in_options_block = False   # True while we are still in the options section
    toctree_has_titlesonly = False
    toctree_has_hidden = False

    for line in lines:
        # Detect start of toctree directive
        if ".. toctree::" in line:
            in_toctree = True
            in_options_block = True
            toctree_has_titlesonly = False
            toctree_has_hidden = False
            result_lines.append(line)
            continue

        if not in_toctree:
            result_lines.append(line)
            continue

        # ---- Inside a toctree ----
        stripped = line.lstrip()
        current_indent = line[: len(line) - len(stripped)] if stripped else "   "

        # Non-indented, non-empty line → we have left the toctree
        if stripped and not line.startswith((" ", "\t")):
            in_toctree = False
            in_options_block = False
            result_lines.append(line)
            continue

        # Blank line — marks the end of the options block
        if not stripped:
            if in_options_block:
                in_options_block = False
                if titlesonly and not toctree_has_titlesonly:
                    result_lines.append("   :titlesonly:")
                if hidden and not toctree_has_hidden:
                    result_lines.append("   :hidden:")
            result_lines.append(line)
            continue

        # Option line (starts with ':')
        if stripped.startswith(":"):
            if stripped.startswith(":titlesonly:"):
                toctree_has_titlesonly = True
            if stripped.startswith(":hidden:"):
                toctree_has_hidden = True
            if max_depth is not None and stripped.startswith(":maxdepth:"):
                result_lines.append(f"{current_indent}:maxdepth: {max_depth}")
            else:
                result_lines.append(line)
            continue

        # First entry line with no preceding blank separator — close options block
        if in_options_block:
            in_options_block = False
            if titlesonly and not toctree_has_titlesonly:
                result_lines.append("   :titlesonly:")
            if hidden and not toctree_has_hidden:
                result_lines.append("   :hidden:")

        # Toctree entry — may be "module.name" or "display <module.name>"
        match = re.match(r"^\s*(?:.*\s+<)?([^<>\s]+)>?\s*$", line)
        if match:
            module_name = match.group(1)

            # Skip hidden modules
            if should_hide_module(module_name, hidden_modules):
                continue

            # Rewrite to short display name
            if short_names:
                short_name = get_short_name(module_name)
                if short_name != module_name:
                    result_lines.append(f"{current_indent}{short_name} <{module_name}>")
                    continue

        result_lines.append(line)

    return "\n".join(result_lines)


def clean_autodocs() -> None:
    """Clean up autodocs RST files."""
    hidden_modules = get_hidden_modules()
    print(f"Hidden modules: {hidden_modules}")
    print(
        f"Flags: delete_hidden={_delete_hidden}, replace_automodule={_replace_automodule}, "
        f"short_display_names={_short_display_names}, top_level_maxdepth={_top_level_maxdepth}, "
        f"rename_titles={_rename_titles}, titlesonly={_titlesonly}, "
        f"use_package_all_definition={_use_package_all_definition}, "
        f"hide_from_sidebar={_hide_from_sidebar}, "
        f"skip_members={len(_skip_members)} module(s)"
    )

    if not AUTODOCS_DIR.exists():
        print(f"Autodocs directory not found: {AUTODOCS_DIR}")
        return

    # Process all RST files
    rst_files = list(AUTODOCS_DIR.glob("*.rst"))
    print(f"Found {len(rst_files)} RST files")

    files_deleted = 0
    files_updated = 0

    for rst_file in rst_files:
        module_name = rst_file.stem  # e.g., 'earthkit.transforms.temporal'

        # --- Step 1: delete hidden/private modules -------------------------
        if _delete_hidden and should_hide_module(module_name, hidden_modules):
            print(f"Deleting: {rst_file.name}")
            rst_file.unlink()
            files_deleted += 1
            continue

        content = rst_file.read_text()
        new_content = content

        # --- Step 2: clean toctree entries ---------------------------------
        # Limit the toctree depth on the top-level package page to
        # _top_level_maxdepth so it only lists subpackage names.
        toctree_depth = _top_level_maxdepth if module_name == MODULE_PREFIX else None
        new_content = clean_toctree(
            new_content,
            hidden_modules,
            max_depth=toctree_depth,
            short_names=_short_display_names,
            titlesonly=_titlesonly,
            hidden=_hide_from_sidebar,
        )

        # --- Step 3: replace automodule with autosummary ------------------
        if _replace_automodule:
            new_content = replace_automodule_with_autosummary(new_content, module_name)

        # --- Step 4: rename page headings ---------------------------------
        if _rename_titles:
            new_content = rename_titles(new_content)

        if new_content != content:
            rst_file.write_text(new_content)
            print(f"Updated: {rst_file.name}")
            files_updated += 1

    print(f"\nSummary: {files_deleted} files deleted, {files_updated} files updated")


if __name__ == "__main__":
    clean_autodocs()
