#!/usr/bin/env python
"""Clean up sphinx-apidoc generated RST files.

This script post-processes the RST files generated by sphinx-apidoc to:
1. Remove private modules (those starting with '_')
2. Remove hidden modules (configured in conf.py)
3. Update toctree entries to use short display names in the sidebar
   while keeping full module paths as page titles
"""

import importlib
import re
import sys
import types
from pathlib import Path

# Ensure the project source tree takes precedence over any installed version of
# the package so that __all__ reflects the current source code.
_SRC_DIR = str(Path(__file__).resolve().parent.parent.parent / "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

# Import configuration from conf.py
import conf

DOCS_DIR = Path(__file__).parent
AUTODOCS_DIR = DOCS_DIR / "autodocs"
MODULE_PREFIX = "earthkit.data"


def get_hidden_modules() -> list[str]:
    """Get the list of hidden modules from conf.py."""
    return getattr(conf, "autodocs_hidden_modules", [])


def is_private_module(module_name: str) -> bool:
    """Check if a module is private (starts with '_')."""
    # Get the last part of the module name
    parts = module_name.split(".")
    return any(part.startswith("_") for part in parts)


def should_hide_module(module_name: str, hidden_modules: list[str]) -> bool:
    """Check if a module should be hidden from documentation.

    Args:
        module_name: Full module name (e.g., 'earthkit.data.aggregate')
        hidden_modules: List of module names to hide (relative to earthkit.data, e.g. ['aggregate', 'internal._utils'])

    Returns:
        True if the module should be hidden.

    """
    if is_private_module(module_name):
        return True

    # Check against hidden modules list
    for hidden in hidden_modules:
        full_hidden = f"{MODULE_PREFIX}.{hidden}"
        # Match exact module or submodules
        if module_name == full_hidden or module_name.startswith(f"{full_hidden}."):
            return True

    return False


def get_short_name(module_name: str) -> str:
    """Get the short display name for a module.

    Args:
        module_name: Full module name (e.g., 'earthkit.data.temporal')

    Returns:
        Short name (e.g., 'temporal')

    """
    if module_name.startswith(f"{MODULE_PREFIX}."):
        return module_name[len(MODULE_PREFIX) + 1 :]
    return module_name


def get_module_api(module_name: str) -> list[str]:
    """Get the public API of a module from its __all__ attribute.

    Dynamically imports the module and returns ``__all__`` if present.

    Args:
        module_name: Full module name (e.g., 'earthkit.data.temporal')

    Returns:
        List of public member names, or empty list if not available.

    """
    try:
        module = importlib.import_module(module_name)
        all_names = list(getattr(module, "__all__", []))
        # Exclude submodule/subpackage entries — those are already represented
        # in the toctree and must not get their own autosummary pages.
        # Exclude dunder names (e.g. __version__) — these are internal and
        # should never appear as individual API pages.
        return [
            name
            for name in all_names
            if not isinstance(getattr(module, name, None), types.ModuleType)
            and not (name.startswith("__") and name.endswith("__"))
        ]
    except ImportError as exc:
        print(f"Warning: could not import {module_name}: {exc}")
        return []


def replace_automodule_with_autosummary(content: str, module_name: str) -> str:
    """Replace the automodule :members: block with an autosummary table.

    The module docstring is preserved via a bare ``.. automodule::`` directive
    (without ``:members:``).  A ``.. autosummary::`` table with a per-module
    ``:toctree:`` subdirectory is appended so that sphinx-build generates a
    dedicated HTML page for every public function.

    Args:
        content: RST file content
        module_name: Full module name (e.g., 'earthkit.data.temporal')

    Returns:
        Updated RST content.

    """
    members = get_module_api(module_name)
    short_name = get_short_name(module_name)

    # Always produce a bare automodule (docstring only — no inherited :members:
    # options) to avoid documenting imported members inline, which would clash
    # with the per-function pages generated by autosummary.
    # The :no-members: / :no-imported-members: directives explicitly override
    # the autodoc_default_options set in conf.py.
    block_lines = [
        f".. automodule:: {module_name}",
        "   :no-members:",
        "   :no-imported-members:",
        "",
    ]

    if members:
        block_lines += [
            f".. currentmodule:: {module_name}",
            "",
            ".. autosummary::",
            "   :toctree: generated/" + short_name,
            "",
        ]
        for member in members:
            block_lines.append(f"   {member}")
        block_lines.append("")

    new_block = "\n".join(block_lines)

    # Replace the entire automodule block (with any autodoc options) that
    # sphinx-apidoc emits.  The block starts with ``.. automodule::`` and
    # continues through consecutive option lines (``   :option:``).
    content = re.sub(
        r"\.\. automodule::[ \t]+" + re.escape(module_name) + r"(?:\n[ \t]+:.*)*\n",
        new_block + "\n",
        content,
    )
    return content


def clean_toctree(content: str, hidden_modules: list[str], max_depth: int | None = None) -> str:
    """Clean up toctree entries in RST content.

    - Removes entries for hidden/private modules
    - Updates entries to use short display names: 'temporal <earthkit.data.temporal>'
    - Optionally overrides :maxdepth: to control how deep the TOC is rendered on the page

    Args:
        content: RST file content
        hidden_modules: List of module names to hide
        max_depth: If set, replaces :maxdepth: in every toctree with this number.
            This only affects the TOC rendering depth on the page; all linked pages
            are still fully built and reachable.

    Returns:
        Updated RST content

    """
    lines = content.split("\n")
    result_lines = []
    in_toctree = False

    for line in lines:
        # Detect start of toctree directive
        if ".. toctree::" in line:
            in_toctree = True
            result_lines.append(line)
            continue

        if in_toctree:
            # Check if we're still in the toctree (indented content or empty line)
            stripped = line.lstrip()
            current_indent = line[: len(line) - len(stripped)]

            # If line is not empty and not indented, we've left the toctree
            if stripped and not line.startswith(" ") and not line.startswith("\t"):
                in_toctree = False
                result_lines.append(line)
                continue

            # Skip empty lines within toctree
            if not stripped:
                result_lines.append(line)
                continue

            # Check if this is a toctree option (starts with :)
            if stripped.startswith(":"):
                if max_depth is not None and stripped.startswith(":maxdepth:"):
                    result_lines.append(f"{current_indent}:maxdepth: {max_depth}")
                else:
                    result_lines.append(line)
                continue

            # This is a toctree entry - extract the module name
            # Entries can be in format: "module.name" or "display <module.name>"
            match = re.match(r"^\s*(?:.*\s+<)?([^<>\s]+)>?\s*$", line)
            if match:
                module_name = match.group(1)

                # Skip hidden modules
                if should_hide_module(module_name, hidden_modules):
                    continue

                # Create short display name entry
                short_name = get_short_name(module_name)
                if short_name != module_name:
                    result_lines.append(f"{current_indent}{short_name} <{module_name}>")
                else:
                    result_lines.append(line)
            else:
                result_lines.append(line)
        else:
            result_lines.append(line)

    return "\n".join(result_lines)


def clean_autodocs():
    """Clean up autodocs RST files."""
    hidden_modules = get_hidden_modules()
    print(f"Hidden modules: {hidden_modules}")

    if not AUTODOCS_DIR.exists():
        print(f"Autodocs directory not found: {AUTODOCS_DIR}")
        return

    # Process all RST files
    rst_files = list(AUTODOCS_DIR.glob("*.rst"))
    print(f"Found {len(rst_files)} RST files")

    files_deleted = 0
    files_updated = 0

    for rst_file in rst_files:
        module_name = rst_file.stem  # e.g., 'earthkit.data.temporal'

        # Delete files for hidden/private modules
        if should_hide_module(module_name, hidden_modules):
            print(f"Deleting: {rst_file.name}")
            rst_file.unlink()
            files_deleted += 1
            continue

        # Clean up toctree entries and replace automodule with autosummary
        content = rst_file.read_text()
        # Limit the toctree depth on the top-level package page to 1 so it only
        # lists subpackage names. All child pages are still fully built.
        toctree_depth = 1 if module_name == MODULE_PREFIX else None
        new_content = clean_toctree(content, hidden_modules, max_depth=toctree_depth)
        new_content = replace_automodule_with_autosummary(new_content, module_name)

        if new_content != content:
            rst_file.write_text(new_content)
            print(f"Updated: {rst_file.name}")
            files_updated += 1

    print(f"\nSummary: {files_deleted} files deleted, {files_updated} files updated")


if __name__ == "__main__":
    # clean_autodocs()
    pass
