name: Code Quality checks for PRs

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    uses: ecmwf/reusable-workflows/.github/workflows/qa-precommit-run.yml@v2
    with:
      skip-hooks: "no-commit-to-branch"
